server:
  port: 8899
  servlet:
    context-path: /resource



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: app-resource


mybatis-plus:
  type-aliases-package: com.mca.server.entity
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl