
server:
  port: 8435
  servlet:
    context-path: /client-manager



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: client-manager


mybatis-plus:
  type-aliases-package: com.mca.client.manager.entity
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl